sudo: required
services:
    -docker

before_install:
    - docker build -t barrybt23/complex-test -f ./client/Dockerfile.dev ./client
    #multiple builds can be installed for testing purposes but we are using one.\

script:
    -docker run -e CI=true barrybt23/complex-test npm test 

after_success:
    - docker build -t barrybt23/multi-client ./client
    - docker build -t barrybt23/multi-nginx ./nginx
    - docker build -t barrybt23/multi-server ./server
    - docker build -t barrybt23/multi-worker ./worker

#Login to  docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

#Take these images and push to docker Hub
    - docker push barrybt23/multi-client
    - docker push barrybt23/multi-nginx
    - docker push barrybt23/multi-server
    - docker push barrybt23/multi-worker




