version: '3'
services: 
    nginx:
        depends_on: [api, client]
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - '3050:80'
    postgres:
        image: 'postgres:latest'
    redis:
        image: 'redis:latest'
    api:
        # depends_on: [postgres]
        build:
            dockerfile: Dockerfile.dev
            #/Context determines the location to use
            context: ./server
        volumes:
            #/bookmark for node_modules so it remains static
            - /app/node_modules
            #/points to the source folder for any changes
            - ./server:/app 
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
    client: 
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes: 
            - /app/node_modules
            - ./client:/app
    worker: 
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        build:
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes: 
            - /app/node_modules
            - ./worker:/app
        